name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  push:
    paths-ignore:
     - '.github/workflows/*'  
jobs:
  get-dataset:
    runs-on: ubuntu-latest
    env:
      DATASET_URL: 'https://datasets.imdbws.com/'
      DATASET_NAME: 'title.basics.tsv'
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Download imdb dataset
        run: wget ${DATASET_URL}${DATASET_NAME}.gz
      - name: Unzip dataset archive
        run: gzip -d ${DATASET_NAME}.gz
      - run: ls -l          
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Check python version
        run: python -v      
      - name: Install dependencies
        run: pip install -r requirements.txt      
      - name: Execute script
        run: python python_script.py
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: movies.txt
          path: movies.txt
