name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  push:
    paths-ignore:
     - '.github/workflows/*'  
jobs:
  get-dataset:
    runs-on: ubuntu-latest
    env:
      DATASET_URL: 'https://datasets.imdbws.com/'
      DATASET_NAME: 'title.basics.tsv'
    steps:      
      - name: Download imdb dataset
        run: wget ${DATASET_URL}${DATASET_NAME}.gz
      - name: Unzip dataset archive
        run: gzip -d ${DATASET_NAME}.gz
      - name: Upload datasets file
        uses: actions/upload-artifact@v4
        with:
          name: dataset-file
          path: ${DATASET_NAME}          
  get-python:
    runs-on: ubuntu-latest
    # env:
    #   secret_api_key: ${{ secrets.SECRETAPI }}
    steps:      
      - name: Get repository code
        uses: actions/checkout@v4
    #   - name: Cache deps
    #     uses: actions/cache@v4
    #     with:
    #       path: where
    #       key: pymodules-${{ hashFiles(**/dependencies.txt) }}      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Check python version
        run: python -v 
     #  - name: Show secret api
     #    run: echo $secret_api_key
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dataset-file
      - name: Execute script
        run: python python_script.py
